### ISSUE TITLE
release workflow triggered directly from tag push even, even when it's deleted

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/support#18]
### Intro

Some time ago we changed the `release` workflow to run release **after** tests passed on CI, i.e `push: tag` condition was moved from `release` to `rake` workflow like this https://github.com/relaton/relaton-iso/commit/669c7defe7d80dd4339a4f2a78d07bc1bc20d78a for all repositories in relaton group

### Problem

Somehow `release` workflow is still triggered directly, here are some incidents:
 - https://github.com/relaton/relaton-iso/actions/runs/5017983425/jobs/8996802261
 - https://github.com/relaton/relaton-bib/actions/runs/5982575634/job/16231798963

But there are many more such cases for sure.

Interestingly if you click on the actual workflow file https://github.com/relaton/relaton-bib/actions/runs/5982552140/workflow
It shows for some reason outdated workflow and a strange message:

<img width="816" alt="Screenshot 2023-08-28 at 3 51 28 PM" src="https://github.com/relaton/support/assets/2169738/28150501-db36-4e89-a823-8fe18ebeec43">

To me, this looks like an issue on GitHub Actions, for `relaton-iso` issue already not resproduces

@andrew2net in case if you will find another such issue could you please just add a link on "run" to this issue

**Comment by andrew2net** [comment]
@CAMOBAP Today I pushed relaton-iso-bib with tag "1.16.1" but it wasn't released automatically.
https://github.com/relaton/relaton-iso-bib/actions/runs/6242827287
I had to run the release GHA manually.
https://github.com/relaton/relaton-iso-bib/actions/runs/6242957120

**Comment by CAMOBAP** [comment]
@andrew2net thanks for the information, unfortunately, I am still out of ideas as to why GitHub actions behave in a such way. It looks like the configuration cached somehow by GHA internally because this time on `rake` workflow wasn't triggered for `relaton-iso-bib` and `release` wasn't triggered by tag

As previously mentioned, `relaton-iso` and `relaton-bib` already works as expected while no changes were done for them, and the configuration there is the same as in `relaton-iso-bib`

**Comment by CAMOBAP** [comment]
Looks like this was some weird issues with GitHub infrastructure we don;t observe it anymore
