### ISSUE TITLE
Errno::ENOENT: No such file or directory @ realpath_rec - D:/a/relaton-calconnect/relaton-calconnect/vendor/bundle/ruby/2.7.0/gems/debase-ruby_core_source-0.10.12/lib

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/support#2]
Happens randomely on windows:

 - https://github.com/relaton/relaton-cli/pull/95/checks?check_run_id=2094281222
 - https://github.com/relaton/relaton-calconnect/runs/2094127354?check_suite_focus=true
 - https://github.com/relaton/relaton-iso-bib/runs/2094547035?check_suite_focus=true

cc @andrew2net I will investigate this bit later, please let me know if you have info about some workaround for it

**Comment by andrew2net** [comment]
@CAMOBAP sorry but I don't have any info about it

**Comment by CAMOBAP** [comment]
@andrew2net np, I will investigate

**Comment by CAMOBAP** [comment]
Looks like not a case anymore, closing
