### ISSUE TITLE
Fix Ruby workflow relating to expressir platform

### ISSUE THREAD

**Issue by ronaldtse** [relaton/support#25]
https://github.com/relaton/relaton-models/pull/51 is failing due to Rubygems version mismatch.

@CAMOBAP can you please help fix the workflows in this repo? Thanks.

**Comment by CAMOBAP** [comment]
Fixed in https://github.com/relaton/support/commit/6126e7346d9be81ec2a23d3e1b36a7cd7c799b87 but because default branch on `support` repo was migrated to master -> main the fix wasn't applied

A mass update started to propagate the fix for all repositories
