### ISSUE TITLE
Scheduled workflows are automatically disabled

### ISSUE THREAD

**Issue by andrew2net** [relaton/support#7]
As per https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. It means a repository should have at least one commit in 60 days. To solve this problem the `flag.txt` file was added. The file was updated every time action ran. https://github.com/relaton/support/blob/92f27b5b390590d67d470a720e09a72a17fc3029/.github/workflows/crawler.yml#L40-L41
But now the `flag.txt` file is updated only if there are any changes in the repo. So the file doesn't do the job it was introduced for.
We need to update the `flag.txt` file even if there aren't any other changes in the repo.
I agree that making an empty commit every day is too much. It would be great if the action can parse a date from the `flag.txt` and make an empty commit only if it is 59 days old.

UPD there is an action that keeps workflow alive https://github.com/marketplace/actions/keepalive-workflow

**Comment by ronaldtse** [comment]
Why don’t we just use the GHA action that automatically extends?

**Comment by andrew2net** [comment]
@ronaldtse yes, we should move to the action. I just didn't find it when we encountered the issue.

**Comment by CAMOBAP** [comment]
I will add [a described workflow](https://github.com/marketplace/actions/keepalive-workflow#via-github-actions-for-github-actions-users) as a separate `keep-alive.yml` so we will be able to integrate it independently

**Comment by andrew2net** [comment]
> I will add [a described workflow](https://github.com/marketplace/actions/keepalive-workflow#via-github-actions-for-github-actions-users) as a separate `keep-alive.yml` so we will be able to integrate it independently

@CAMOBAP thank you. In this case, we can remove the `flag.txt`.

**Comment by CAMOBAP** [comment]
Additionally, to keep-alive workflows I refactored some workflows to avoid duplication:
 - https://github.com/relaton/relaton-data-3gpp/pull/3
 - https://github.com/relaton/relaton-data-iec/pull/4 (to be updated)

@andrew2net I need your help with reviews of:
 - https://github.com/relaton/relaton-data-ieee/pull/2
 - https://github.com/relaton/relaton-data-iana/pull/3
 - https://github.com/relaton/relaton-data-rfcsubseries/pull/2
 - https://github.com/relaton/relaton-data-bipm/pull/30
 - https://github.com/relaton/relaton-data-rfcs/pull/2
 - https://github.com/relaton/relaton-data-iho/pull/17
 - https://github.com/relaton/relaton-data-oasis/pull/3
 - https://github.com/relaton/relaton-data-3gpp/pull/3
 - https://github.com/relaton/relaton-data-ecma/pull/2
 - https://github.com/relaton/relaton-data-iso/pull/14

@andrew2net also feel free to report issues for me in relaton/support if some workflows aren't flexible enough. I will try to extend them to minimize duplication of the CI configuration

@ronaldtse could you please give me write access
 - relaton/relaton-data-itu-r
 - relaton/relaton-data-nist
 - relaton/relaton-data-calconnect

To be fixed (by me):
 - https://github.com/relaton/relaton-data-iec/pull/4

**Comment by CAMOBAP** [comment]
All data repos now have `keep-aliwe` workflow
