### ISSUE TITLE
Index is not pushed

### ISSUE THREAD

**Issue by andrew2net** [relaton/support#9]
Despite there being updated `index.yaml` and `index.zip` a new commit isn't created  and the update isn't pushed
https://github.com/relaton/relaton-data-iho/actions/runs/4651357108/jobs/8230909614#step:6:57

**Comment by CAMOBAP** [comment]
@andrew2net as far as I see this run was triggered but Pull Request. It seams correct behavior to me that we not commit data from pull request.

Let's imagine that we have a several PR in development (potentially with issues) why should we commit data based on it?

Once you will merge your PR data will be committed to repo

Correct me if current behavior is wrong

**Comment by andrew2net** [comment]
@CAMOBAP ok, thanks for the clarification.
